# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'acf59d495926c82c5d619c4f979d2ca6'
  config.secret_key = '1ab0e1be3d62a1cdf0772bc3f56b5601'
  config.default_from = 'bellup17@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
